repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.7
    hooks:
      - id: uv-lock
      
  - repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.12.8
    hooks:
    # Run the linter.
      - id: ruff-check
        types_or: [ python, pyi ]
        args: [ --fix ]
    # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.403
    hooks:
      - id: pyright

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: .venv/Scripts/pytest.exe tests
        language: python
        pass_filenames: false
        always_run: true
        exclude: ^output/assignments\.json$