line-length = 88  

[lint]
select = ["E", "F", "I", "B", "UP", "C4", "SIM", "RUF"]
ignore = ["E501"]  # ignore line length if black is handling it

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
